sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    # - openssl command
    # - curl https://sdk.cloud.google.com | bash > dev/null;
    # - source $HOME/google-cloud-sdk/path.bash.inc
    # - gcloud components update kubectl
    # - gcloud auth activate-service-account --key-file service-account.json
    # - gcloud config set project {project-id on gcloud}
    # - gcloud config set compute/zone {location}
    # - gcloud container clusters get-credentials multi-cluster
    - echo $SHA
    # - $SHA
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker build -t surajsingla333/kubernet-test -f ./client/Dockerfile.dev ./client

script:
    - docker run surajsingla333/kubernet-test npm test -- --coverage

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: kubernetes