sudo: required
services:
    - docker

before_install:
    - docker build -t surajsingla333/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run surajsingla333/react-test npm test -- --coverage

after_success:
    - docker build -t surajsingla333/complex-client:v1 ./client 
    - docker build -t surajsingla333/complex-nginx ./nginx 
    - docker build -t surajsingla333/complex-server ./server 
    - docker build -t surajsingla333/complex-worker ./worker 

    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push on docker hub
    - docker push surajsingla333/complex-client:v1
    - docker push surajsingla333/complex-nginx
    - docker push surajsingla333/complex-server
    - docker push surajsingla333/complex-worker

# AWS Production setup and commands
# deploy:
#     provider: elasticebeanstalk
#     region: us-west-1
#     app: multi-docker
#     env: MultiDocker-env
#     bucket_name: elastibeanstalk-us-west-1-306476627547
#     bucket_path: docker-multi
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key:
#         secure: $AWS_SECRET_KEY