version: '3'
services:
    db:
        image: 'postgres:latest'
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
    mongo:
        image: mongo
        restart: always
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=root
        #     - MONGO_INITDB_ROOT_PASSWORD=rootPass

    adminmongo:
        image: "mrvautin/adminmongo"
        ports:
            - '1234:1234'
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '4000:80'
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        depends_on: 
            - db
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=db
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
            - MONGOHOST=mongo
            - MONGOPORT=27017
            - MONGODATABASE=mongo
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes: 
            - /app/node_modules
            - ./worker:/app